### ISSUE TITLE
Push to supermarket

### ISSUE THREAD

**Issue by spuder** [bdangit/chef-influxdb#101]
Any plans to push an updated version to the supermarket? It is currently at version 0.1.0

**Comment by bdangit** [comment]
? it should be at version. 4.0.1 

https://supermarket.chef.io/cookbooks/influxdb

**Comment by spuder** [comment]
Maybe I had my cookbooks mixed up. Looking again, It does appear correct.

**Comment by bdangit** [comment]
cool. :smile:
