### ISSUE TITLE
Add json-write-enabled to https section in config

### ISSUE THREAD

**Issue by cyberflow** [bdangit/chef-influxdb#104]
Hello,

Please add `json-write-enabled` to config file for get ability to use old method write path. 
I known that it's a deprecated functionality but it's official option in 0.11 version (https://github.com/influxdata/influxdb/pull/5512).

Thanks.

**Comment by bdangit** [comment]
hey @cyberflow 

You should be able to just add in the setting into node attributes and as long as you use `influxdb_config` which is in the `default.rb`, it will regenerate the config as desired.

```ruby
node.default['influxdb']['config']['http'] = {
  'json-write-enabled' => true
}
include_recipe 'influxdb::default'
```

**Comment by bdangit** [comment]
this will work also

node.override['influxdb']['config']['http'] = {
  'json-write-enabled' => true
}
include_recipe 'influxdb::default'

**Comment by cyberflow** [comment]
Thanks.
