### ISSUE TITLE
systemd fails to start on RHEL7.1

### ISSUE THREAD

**Issue by devilldog** [bdangit/chef-influxdb#111]
Hi All,used the cookbook to install influx everything worked fine except startup 
[root@livvsdinfluxdb01 ~]# systemctl status influxdb
● influxdb.service - InfluxDB is an open-source, distributed, time series database
   Loaded: loaded (/usr/lib/systemd/system/influxdb.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Fri 2016-06-24 14:08:39 EDT; 29min ago
     Docs: https://docs.influxdata.com/influxdb/
  Process: 1779 ExecStart=/bin/sh -c /usr/bin/influxd -config /etc/influxdb/influxdb.conf ${INFLUXD_OPTS} >>${STDOUT} 2>>${STDERR} (code=exited, status=1/FAILURE)
 Main PID: 1779 (code=exited, status=1/FAILURE)

Jun 24 14:08:39 livvsdinfluxdb01...net systemd[1]: Unit influxdb.service entered failed state.
Jun 24 14:08:39 livvsdinfluxdb01...net systemd[1]: influxdb.service failed.
Jun 24 14:08:39 livvsdinfluxdb01...net systemd[1]: influxdb.service holdoff time over, scheduling...rt.
Jun 24 14:08:39 livvsdinfluxdb01...net systemd[1]: start request repeated too quickly for influxd...ice
Jun 24 14:08:39 livvsdinfluxdb01...net systemd[1]: Failed to start InfluxDB is an open-source, di...se.
Jun 24 14:08:39 livvsdinfluxdb01...net systemd[1]: Unit influxdb.service entered failed state.
Jun 24 14:08:39 livvsdinfluxdb01...net systemd[1]: influxdb.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

however running /bin/sh -c /usr/bin/influxd -config /etc/influxdb/influxdb.conf
influx starts just fine.

**Comment by bdangit** [comment]
Thanks for reporting this. Can you first let us know what version of influxdb you are running? There might have been some changes since 0.9.

**Comment by devilldog** [comment]
0.13

**Comment by bdangit** [comment]
hey @devilldog,

I ran a test kitchen against centos 7.1.  The cookbook does install 0.13 of influxdb and it starts up just fine.

## system info
```bash
[kitchen@7ab3384ed457 ~]$ influxd version
InfluxDB v0.13.0 (git: 0.13 e57fb88a051ee40fd9277094345fbd47bb4783ce)
[kitchen@7ab3384ed457 ~]$ cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
```

## after first convergence
```bash
[kitchen@7ab3384ed457 ~]$ systemctl status influxdb
● influxdb.service - InfluxDB is an open-source, distributed, time series database
   Loaded: loaded (/usr/lib/systemd/system/influxdb.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-07-04 07:02:23 UTC; 1min 17s ago
     Docs: https://docs.influxdata.com/influxdb/
 Main PID: 721 (sh)
   CGroup: /system.slice/influxdb.service
           ├─721 /bin/sh -c /usr/bin/influxd -config /etc/influxdb/influxdb.conf  >>/dev/null 2>>...
           └─722 /usr/bin/influxd -config /etc/influxdb/influxdb.conf
```

## Stopped the service
```bash
[kitchen@7ab3384ed457 ~]$ sudo systemctl stop influxdb
[kitchen@7ab3384ed457 ~]$ systemctl status influxdb
● influxdb.service - InfluxDB is an open-source, distributed, time series database
   Loaded: loaded (/usr/lib/systemd/system/influxdb.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Mon 2016-07-04 07:03:50 UTC; 1s ago
     Docs: https://docs.influxdata.com/influxdb/
  Process: 721 ExecStart=/bin/sh -c /usr/bin/influxd -config /etc/influxdb/influxdb.conf ${INFLUXD_OPTS} >>${STDOUT} 2>>${STDERR} (code=killed, signal=TERM)
 Main PID: 721 (code=killed, signal=TERM)
   CGroup: /system.slice/influxdb.service
```

## Started the service
```bash
[kitchen@7ab3384ed457 ~]$ sudo systemctl start influxdb
[kitchen@7ab3384ed457 ~]$ systemctl status influxdb
● influxdb.service - InfluxDB is an open-source, distributed, time series database
   Loaded: loaded (/usr/lib/systemd/system/influxdb.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-07-04 07:04:05 UTC; 2s ago
     Docs: https://docs.influxdata.com/influxdb/
 Main PID: 762 (sh)
   CGroup: /system.slice/influxdb.service
           ├─762 /bin/sh -c /usr/bin/influxd -config /etc/influxdb/influxdb.conf  >>/dev/null 2>>...
           └─763 /usr/bin/influxd -config /etc/influxdb/influxdb.conf
```

**Comment by devilldog** [comment]
Thanks I will double check, our system is pretty vanilla, let me rebuild and report back.

**Comment by bdangit** [comment]
hi @devilldog,

going to close this ticket out.  Feel free to reopen if problem persists.

**Comment by blackbutler320** [comment]
facing issue with Raspberry Pi 2 
   sudo systemctl status parity
● parity.service - Ethereum Parity client daemon
   Loaded: loaded (/etc/systemd/system/parity.service; disabled)
   Active: failed (Result: start-limit) since Fri 2017-07-07 19:58:10 IST; 7min ago
 Main PID: 630 (code=killed, signal=ILL)

Jul 07 19:58:10 ethnode-e3b0c442 systemd[1]: parity.service holdoff time ove....
Jul 07 19:58:10 ethnode-e3b0c442 systemd[1]: Stopping Ethereum Parity client....
Jul 07 19:58:10 ethnode-e3b0c442 systemd[1]: Starting Ethereum Parity client....
Jul 07 19:58:10 ethnode-e3b0c442 systemd[1]: parity.service start request re....
Jul 07 19:58:10 ethnode-e3b0c442 systemd[1]: Failed to start Ethereum Parity....
Jul 07 19:58:10 ethnode-e3b0c442 systemd[1]: Unit parity.service entered fai....
Jul 07 20:05:15 ethnode-e3b0c442 systemd[1]: Stopped Ethereum Parity client ....
Jul 07 20:05:23 ethnode-e3b0c442 systemd[1]: Stopped Ethereum Parity client ....
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by bdangit** [comment]
Hi @blackbutler320, it looks like the error you are reporting is for a different service other than influxd.  Does that service prevent influxd from starting?
