### ISSUE TITLE
Update apt dependency

### ISSUE THREAD

**Issue by julian7** [bdangit/chef-influxdb#125]
apt-3.0.0 has been released on Mar 1, 2015. Can you update apt dependency from ~> 2.9.2 to something like >=2.9.2? According to the apt cookbook's changelog, breaking functionality changes were minimal: dropping chef 10 compatibility, and apt cacher NG support for debian 6.x and ubuntu 10.4, which are fair.

By the way, I'm seeing dependencies like "apt >= 0.0.0". Erlang cookbook specifies "apt >= 1.7.0". So in my opinion this change will not break functionality.

**Comment by bdangit** [comment]
Hey @julian7.  Thanks for the suggestion.  I don't want to leave them floating like ">=" since its hard to make any guarantees that the cookbook will still work if there are any major changes.   As I go about #124 , I'll test with latest versions of the cookbook dependencies still using "~>".

**Comment by julian7** [comment]
It's nice to see familiar faces ;) I'm totally with you, but I also understand most of the people don't treat that cookbook very well. 3.0.0 has not changed too much since 2.7.x, but this particular fact had to be evaluated manually.

**Comment by bdangit** [comment]
hah, likewise.

Is your requirement you want apt 3.0.0? or is it okay for me to just use latest and greatest which is currently 4.0.0?

take a look at  https://github.com/bdangit/chef-influxdb/pull/124/files#diff-9fd042d4cd1e8f82894bbd7dffb313ecR19 and tell me if this is okay.

**Comment by julian7** [comment]
This is an awesome idea. The upgrade was long overdue, and anyway, we can't hold back innovation :)

**Comment by bdangit** [comment]
Lol. Love it. I'll steal the line when people tell me that we have to rollback. 

;)

**Comment by bdangit** [comment]
influxdb 5.0.0 is merged and uploaded to supermarket.  have fun cooking!
