### ISSUE TITLE
Error installing influxdb package using chef-client 12.19.33

### ISSUE THREAD

**Issue by teknofire** [bdangit/chef-influxdb#141]
I get the following error when using chef-client 12.19.33

https://gist.github.com/teknofire/858dc84708a3724bf46cf81c99823102

with just a basic recipe of

```
include_recipe 'influxdb::default'
```

Converging with 12.18.31 works as expected.

**Comment by bdangit** [comment]
@teknofire thanks for reporting.  Will take a look.

FYI, I checked the [changelog for chef-client](https://github.com/chef/chef/blob/master/CHANGELOG.md#v121935-2017-02-22) and there does not appear to be any changes related to `package` or `deb_package` changing.

Just to better undesrtand your scenario, can you provide OS, OS Version, what type of way you are installing influxdb and what versino of Influxdb you are trying to do use?

**Comment by teknofire** [comment]
So this is using Ubuntu 16.04 and the `package` method and with version `1.2.0-1` 

I'm currently not overriding any attributes from the influxdb cookbook.

**Comment by teknofire** [comment]
Here is an example repo that has replicates the error I'm seeing

https://github.com/teknofire/influxdb-test-cookbook

**Comment by teknofire** [comment]
Looks like https://github.com/chef/chef/issues/5836 is the issue for 12.19.33 and should be fixed in the next chef-client release.

**Comment by teknofire** [comment]
Just tested with chef-client 12.19.36 and it's working as expected again.

**Comment by bdangit** [comment]
Cool! Glad chef cut a new release.

**Comment by gsaslis** [comment]
what a mess... After v13 has come out it's even harder to find release notes for versions after 12.19.33...

Nothing useful here: https://docs.chef.io/release_notes.html
Nothing useful here: https://github.com/chef/chef/blob/master/CHANGELOG.md

:( 

When wanting to pin to major version 12 (after 13 came out) I visited above links and found that 12.19.33 was the latest version (it is not! at least for ubuntu which i'm on), which led me back to this regression.

**Comment by bdangit** [comment]
@gsaslis hah hurray open source. :) clarity always helps.
