### ISSUE TITLE
Make 'retry' argument of InfluxDB::Client configurable

### ISSUE THREAD

**Issue by vills** [bdangit/chef-influxdb#150]
Currently after #77 `retry` argument passed to `InfluxDB::Client.new` is 10. Sure, it is not possible for any influxdb installation. Please, do this argument configurable by resource properties.

**Comment by bdangit** [comment]
Hi @vills, thanks for reporting this.  Should be an easy enhancement to make.

**Comment by bdangit** [comment]
#161 has been merged.
