### ISSUE TITLE
Activate http-auth security

### ISSUE THREAD

**Issue by Lechucico** [bdangit/chef-influxdb#163]
I would like to know how to set `auth-enabled = true`. I've created an admin and user but I can still bypass authentication for accessing databases. 

How I can make authentication mandatory?

**Comment by Lechucico** [comment]
Solved executing this on my own recipe:

```
node.override['influxdb']['config']['http']['auth-enabled'] = true

influxdb_config node['influxdb']['config_file_path'] do
  config node['influxdb']['config']
  notifies :restart, 'service[influxdb]', :delayed
end
```

**Comment by bdangit** [comment]
hey @Lechucico.  Yes, that is a way to do it.  If you look in one of our Test-Kitchen setups, we do show how you can modify the config file by doing what you just did.

https://github.com/bdangit/chef-influxdb/blob/master/test/fixtures/cookbooks/influxdb-test/recipes/config_change.rb#L1-L9
