### ISSUE TITLE
constant Custom resource influxdb_admin from cookbook influxdb::InfluxDB

### ISSUE THREAD

**Issue by djaboxx** [bdangit/chef-influxdb#164]
================================================================================
    Error executing action `create` on resource 'influxdb_admin[admin]'
    ================================================================================
    
    NameError
    ---------
    uninitialized constant Custom resource influxdb_admin from cookbook influxdb::InfluxDB
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/influxdb/resources/admin.rb:27:in `rescue in block in class_from_file'
    /var/chef/cache/cookbooks/influxdb/resources/admin.rb:22:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/alpha_influxdb/recipes/influxdb.rb
    
     22: influxdb_admin 'admin' do
     23:   password influxdb_admin_credentials[:password]
     24:   action :create
     25: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/alpha_influxdb/recipes/influxdb.rb:22:in `from_file'
    
    influxdb_admin("admin") do
      action [:create]
      default_guard_interpreter :default
      declared_type :influxdb_admin
      cookbook_name "alpha_influxdb"
      recipe_name "influxdb"
      password "< redacted >"
      username "admin"
    end
    
    System Info:
    ------------
    chef_version=13.6.4
    platform=ubuntu
    platform_version=14.04
    ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
    program_name=chef-client worker: ppid=19659;start=18:05:31;
    executable=/opt/chef/bin/chef-client

**Comment by djaboxx** [comment]
nm, probably my bad.... naming clash.

**Comment by bdangit** [comment]
Ah! Yep that could turn a wrench during resource buildtime. Glad everything
works!
