### ISSUE TITLE
Register on chef supermarket

### ISSUE THREAD

**Issue by odolbeau** [bdangit/chef-influxdb#23]
You should probably register your cookbook on the chef supermarket :
https://supermarket.getchef.com/dashboard

**Comment by BarthV** [comment]
:up:

**Comment by BarthV** [comment]
Ok ... now someone put yet-another-cookbook on supermarket ... And it's a real basic & trivial cookbook !
https://supermarket.chef.io/cookbooks/influxdb
https://github.com/zeroXten/influxdb-chef

Now we have to deal with him to take back the name for this one ... good luck now.

**Comment by BarthV** [comment]
Please contact @zeroXten and release this on supermarket :)

please :'(

**Comment by jakedavis** [comment]
@zeroXten, if you don't mind handling the uploading bits, you can upload it under your user account and that's just fine by me. Does that seem like a fair compromise? Alternatively, if someone PR'd a Makefile with all the bits needed to upload automagically, I could take another swing at it, but we don't have a particular instance in maintaining a Supermarket upload unfortunately :(

**Comment by zeroXten** [comment]
I have created an informational issue #53 to say that I've pointed supermarket to this cookbook.

Having said that, now that I'm trying to actually use it I'm hitting all sorts of crazy problems. So, what I'm going to do is fork this cookbook, fix up a few things, submit a few PRs then point supermarket to my fork as it looks like issues don't get updated here particularly often.

**Comment by bdangit** [comment]
closing this with the caveat that additional work needs to automate newer versions of the cookbook. will create a new issue to auto-version and publish to supermarket.
