### ISSUE TITLE
Use gem 'toml-rb' instead of 'toml'

### ISSUE THREAD

**Issue by alvaromorales** [bdangit/chef-influxdb#63]
Development of the `toml` gem has not been active in a while, despite bugs (see https://github.com/jm/toml/issues/41).

I've had good experiences with [toml-rb](https://github.com/eMancu/toml-rb). The latest release was on 6/12. Have you considered using it instead?

**Comment by jakedavis** [comment]
Hey @alvaromorales, sounds like it'd be a good idea to switch to toml-rb. If you'd PR it we'd be very grateful :)

**Comment by alvaromorales** [comment]
Thanks! Lmk what you think.

**Comment by fishnix** [comment]
:+1: please! :)

**Comment by bdangit** [comment]
happy to merge the PR if it can be de-conflicted.

**Comment by alvaromorales** [comment]
Great, see #98
