### ISSUE TITLE
Support dropped for chef <12.5

### ISSUE THREAD

**Issue by shortdudey123** [bdangit/chef-influxdb#83]
Was dropping support for chef <12.5 intended?
See https://github.com/SimpleFinance/chef-influxdb/pull/81

**Comment by jakedavis** [comment]
Oof. That's not good.

@shortdudey123, would simply renaming `property` back to `attribute` fix the issue for Chef 12 citizens at less than 12.5? We don't use Chef 12 so I'm a bit out of my depth here.

**Comment by gadgetmg** [comment]
Sorry about that... Is >= 12.1 support okay? If so, we can use the `compat_resource` cookbook, otherwise I can rewrite the resources in the older resource/provider format.

**Comment by shortdudey123** [comment]
@jakedavis quite possibly yes, didn't look at all the changes in the refactor to verify that was the only one

@gadgetmg fine by me as i am using 12.4.1, not sure about the rest of the community that uses the cookbook though

**Comment by rjangid1** [comment]
Hi guys, we are using chef 11.18.12 and the cookbook is breaking for us due to `property` method. Is there any easy fix for this?

**Comment by fishnix** [comment]
Hi @rjangid1, this cookbook currently only supports 12.x on master.  I'm not sure if we want to backport for older Chef clients.   I'll let @bdangit weigh in. :+1:

**Comment by bdangit** [comment]
hrmm...why wouldn't you want to use the awesome chef 12??? :monkey_face: 

Anyways, can you fill us in on the `property` method?  I'm not entirely sure about what you are seeing as an error.  Also, has this cookbook ever supported chef 11?

**Comment by fishnix** [comment]
@bdangit: @rjangid1 is talking about the new form of custom resources that was released in [Chef 12.5](https://www.chef.io/blog/2015/10/08/chef-client-12-5-released/).  I do recall that this breaks anything older than 12.x.  It would require some research to see if we can support both.

**Comment by bdangit** [comment]
@fishnix: oh i see.... we have already moved into the new way of creating custom resources.  This will be tricky to support for Chef 11 then.

**Comment by fishnix** [comment]
My preference is to support Chef 12.x+ officially and do best effort on anything older.  The compat_resource cookbook _might_ work for older clients, but in the interest of time and making a cookbook that works well for the majority of folks, that would be my preference.  Thoughts @bdangit ?

**Comment by shortdudey123** [comment]
Maybe it would be good to find where the break occurred, and mention what commit ID to go for if you use Chef 11

**Comment by rjangid1** [comment]
The error I'm getting right now with Chef 11.18 is below. I'm not familiar with Ruby but will try to experiment with changes needed to support the older version.
```
NoMethodError
-------------
undefined method `property' for #<Class:0x0000000407b828>

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/influxdb/resources/admin.rb:22:in `class_from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/influxdb/resources/admin.rb:

 15:  # distributed under the License is distributed on an "AS IS" BASIS,
 16:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 17:  # See the License for the specific language governing permissions and
 18:  # limitations under the License.
 19:  #
 20:  # Resource for InfluxDB cluster admin
 21:  
 22>> property :username, String, name_property: true
 23:  property :password, String
 24:  property :auth_username, String, default: 'root'
 25:  property :auth_password, String, default: 'root'
 26:  
 27:  action :create do
 28:    unless password
 29:      Chef::Log.fatal('You must provide a password for the :create action on this resource!')
 30:    end
 31: 
```

**Comment by rjangid1** [comment]
I found the commit ID but I guess RHEL platform was not supported that time so couldn't test fully.

**Comment by bdangit** [comment]
@rjangid1 are you referring to this commit id? https://github.com/bdangit/chef-influxdb/tree/3738a7b16eb12313034490280653a0959ef7b73a

If so, the work to support 11 is not going to happen anytime soon. Welcome PRs to get it supported however.

**Comment by bdangit** [comment]
closing this as current support to date is for 12.1 and above. 

Highly recommend to upgrade to 12.
