### ISSUE TITLE
Creating Admin user

### ISSUE THREAD

**Issue by qgriffith** [bdangit/chef-influxdb#86]
When trying to create an admin user with

influxdb_admin 'admin' do
  password 'pass'
  action :create
end

The recipe fails with the following error

had an error: NoMethodError: undefined method `get_cluster_admin_list' for #<InfluxDB::Client:0x00000007e2fa70>

**Comment by bdangit** [comment]
Is this still an issue?  We have functional tests against this.

https://github.com/bdangit/chef-influxdb/blob/master/test/integration/default/serverspec/default_spec.rb#L66-L73

**Comment by bdangit** [comment]
closing because of above test.  re-open if persist.
