### ISSUE TITLE
Config out of date again at 0.9.6.1

### ISSUE THREAD

**Issue by donaldguy** [bdangit/chef-influxdb#89]
For starters the package has moved the default config install location to `/etc/influxdb/influxdb.conf` so this should probably be the value of `node.default['influxdb']['config_file_path']`

The content obviously has also changed

corrected for comments and the TOML gem undesirably alphabetizing the sections, here is the diff from what gets installed with the package to what's currently generated from your default attributes:

```diff
diff --git a/influxdb.alphabitized.conf b/influxdb.generated.conf
index 8fe6836..4270247 100644
--- a/influxdb.alphabitized.conf
+++ b/influxdb.generated.conf
@@ -8,7 +8,7 @@ https-enabled = false

 [cluster]
 shard-writer-timeout = "5s"
-write-timeout = "10s"
+write-timeout = "5s"

 [collectd]
 enabled = false
@@ -22,24 +22,22 @@ recompute-no-older-than = "10m"
 recompute-previous-n = 2

 [data]
-dir = "/var/lib/influxdb/data"
+dir = "/var/opt/influxdb/data"
 max-wal-size = 104857600
-wal-dir = "/var/lib/influxdb/wal"
+wal-dir = "/var/opt/influxdb/wal"
+wal-enable-logging = true
 wal-flush-interval = "10m"
-wal-logging-enabled = true
 wal-partition-flush-delay = "2s"

 [[graphite]]
 enabled = false

 [hinted-handoff]
-dir = "/var/lib/influxdb/hh"
+dir = "/var/opt/influxdb/hh"
 enabled = true
 max-age = "168h"
 max-size = 1073741824
-purge-interval = "1h"
 retry-interval = "1s"
-retry-max-interval = "1m"
 retry-rate-limit = 0

 [http]
@@ -54,14 +52,12 @@ write-tracing = false

 [meta]
 bind-address = ":8088"
-cluster-tracing = false
 commit-timeout = "50ms"
-dir = "/var/lib/influxdb/meta"
+dir = "/var/opt/influxdb/meta"
 election-timeout = "1s"
 heartbeat-timeout = "1s"
 hostname = "localhost"
 leader-lease-timeout = "500ms"
-raft-promotion-enabled = true
 retention-autocreate = true

 [monitor]
@@ -76,10 +72,5 @@ enabled = false
 check-interval = "30m"
 enabled = true

-[shard-precreation]
-advance-period = "30m"
-check-interval = "10m"
-enabled = true
-
 [[udp]]
 enabled = false
```

**Comment by bdangit** [comment]
:+1:  tried to address some of these in this PR #88 

It would be nice if we could gaining more traction with this cookbook.  Perhaps the owner could select a few members from the community to help.

**Comment by jakedavis** [comment]
Hello. 

I have been out for nearly a month. We do not use this cookbook and thus maintaining it is not a huge priority for us. I agree getting the community involved would be a good step. I'll review #88, but if either of you is interested in helping maintain this cookbook, that would be swell. I'll open an issue and link it back here, as well.

Thanks.

**Comment by bdangit** [comment]
Hrmm it seems as influxdb progresses forward, these config diffs are likely to happen.  Seeking suggestions on how we can be a bit more fluid with creating configs.  

One way I can think of is if the ['config'] is empty, then we can just generate a new config dynamically from the binary.  Store the contents of this back into the attribute and save the node attributes on completion of node convergence.

**Comment by bdangit** [comment]
this was merged https://github.com/bdangit/chef-influxdb/pull/102 for 0.10.0

w.r.t. my last comment on dynamic generation.  Would be a lot of effort for very little ROI.  The easiest thing to do is just to ensure test kitchen setups for your desired setup is correct.  Think "application wrapper" cookbook design.
