### ISSUE TITLE
Seeking maintainers

### ISSUE THREAD

**Issue by jakedavis** [bdangit/chef-influxdb#92]
Per #89, there is some concern about a lack of maintainers on this cookbook. We do not use this cookbook, and thus would like someone else to take the reins. This can be anywhere from being added as a collaborator to transferring ownership.

Anyone interested in this?

**Comment by bdangit** [comment]
@jakedavis I'll be happy to be a maintainer or own it.

**Comment by jakedavis** [comment]
Okay, wunderbar. Do you have a preference either way?

**Comment by bdangit** [comment]
alright give me the whole cookbook.  🦁

**Comment by jakedavis** [comment]
You'll need to delete your fork first. I transferred it to myself in the interim because apparently you can only transfer organization repos to yourself for now. Once the fork's gone I'll transfer it to you :)

**Comment by bdangit** [comment]
done.

**Comment by bdangit** [comment]
awesome thanks @jakedavis

**Comment by bdangit** [comment]
opening up for anyone who also would like to collaborate.  preventing the same SoPF.

**Comment by fishnix** [comment]
@bdangit We would be interested in collaborating as well at the very least to reduce the SPoF.  We also wrote the [telegraf cookbook](https://github.com/NorthPage/telegraf-cookbook) which is similar to this one.  @tenyo may also be interested in joining.  We are currently interested in getting https://github.com/bdangit/chef-influxdb/issues/63 resolved as it conflicts with the telegraf cookbook's install of `toml-rb` and would be happy to start helping there.

**Comment by bdangit** [comment]
hey @fishnix, sounds good.  I'll add you. And since we have more than one, we should generally follow [4eyes](https://en.m.wikipedia.org/wiki/Four-eye_principle) rule before merging in any PRs. :)

**Comment by fishnix** [comment]
Sounds good! :+1:

**Comment by bdangit** [comment]
done.
