### ISSUE TITLE
service influxdb not restart after config changes.

### ISSUE THREAD

**Issue by cyberflow** [bdangit/chef-influxdb#94]
service influxdb not restart after config changes.

**Comment by fishnix** [comment]
Hi @cyberflow - are you running from master or one of the released versions?  It looks like there was some work done for https://github.com/bdangit/chef-influxdb/issues/70 that is related.  Thanks!

**Comment by bdangit** [comment]
If i'm not mistaken, but 0.9.5+ on RHEL 7 (systemd), would restart the service on its own if there are config changes.  Please don't quote me on this though.  Will have to play around again and see what happens.

**Comment by cyberflow** [comment]
Hi @fishnix. Yes it's same. 
@bdangit : i use ubuntu 14.04 which not have systemd =(
