### ISSUE TITLE
error while installing cookbook 

### ISSUE THREAD

**Issue by rjangid1** [bdangit/chef-influxdb#96]
Hi I am trying to install influxdb cookbook on centos box and got this error.  I checked the code and property method has not been defined anywhere. 

```
NoMethodError
-------------
undefined method `property' for #<Class:0x0000000407b828>

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/influxdb/resources/admin.rb:22:in `class_from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/influxdb/resources/admin.rb:

 15:  # distributed under the License is distributed on an "AS IS" BASIS,
 16:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 17:  # See the License for the specific language governing permissions and
 18:  # limitations under the License.
 19:  #
 20:  # Resource for InfluxDB cluster admin
 21:  
 22>> property :username, String, name_property: true
 23:  property :password, String
 24:  property :auth_username, String, default: 'root'
 25:  property :auth_password, String, default: 'root'
 26:  
 27:  action :create do
 28:    unless password
 29:      Chef::Log.fatal('You must provide a password for the :create action on this resource!')
 30:    end
 31: 
```

**Comment by cyberflow** [comment]
What chef client version you use?
I think you need chef 12.X

**Comment by rjangid1** [comment]
Yeah.  Unfortunately we are still using chef 11.18. And node is having centos.  I tried older commits but I guess there was no rhel platform support till October.  Could you suggest any workaround for supporting older version of Chef

**Comment by fishnix** [comment]
Thanks for reaching out @rjangid1!  This cookbook on `master` currently requires chef-client 12.5+.    (https://www.chef.io/blog/2015/10/08/chef-client-12-5-released/).  It looks like older tagged versions of the cookbook have an LWRP which may solve your issue:  https://github.com/bdangit/chef-influxdb/tree/2.4.0.  We have a few issues regarding supporting older clients, so I'm going to close this one.
