### ISSUE TITLE
update supermarket

### ISSUE THREAD

**Issue by bdangit** [bdangit/chef-influxdb#97]
https://supermarket.chef.io/cookbooks/influxdb is pointing to 2.6.0.

Need to get a new version up.

**Comment by fishnix** [comment]
:+1:

**Comment by Kasen** [comment]
@zeroXten Can you release new version of this cookbook to the supermarket, please?

**Comment by bdangit** [comment]
@zeroxten if you give me rights to push, I will automate the push with wercker.  (note: I know nothing how cookbook authorizations work on supermarket).

**Comment by bdangit** [comment]
I tried to do a push, however, I'm not authorized to upload the cookbook.  

```
E: Stove experienced an error!
E: ChefAPI::Error::HTTPUnauthorizedRequest
E: The Chef Server requires authorization. Please ensure you have specified the correct client name and private key. If this error continues, please verify the given client has the proper permissions on the Chef Server.

    {"error_code"=>"UNAUTHORIZED", "error_messages"=>["You are not authorized to upload this cookbook."]}

```

**Comment by fishnix** [comment]
if you have an account in the supermarket @bdangit, @zeroxten can transfer it to you and you can make me a collaborator

![screen shot 2016-01-22 at 11 34 01 am](https://cloud.githubusercontent.com/assets/508237/12516594/3ce2c648-c0fc-11e5-923a-b77ac0348df4.png)

**Comment by bdangit** [comment]
done.

@fishnix you're added.
